# APPLIACTIONS BLUR
#windowrule = noblur, tag:multimedia_video*
#windowrule = opacity 1.0, tag:multimedia_video*
#windowrule = opacity 0.8, tag:settings*
windowrule = opacity 0.8, match:class (org.gnome.Nautilus)
windowrule = opacity 0.9, match:class (gedit|org.gnome.TextEditor|mousepad)
windowrule = opacity 0.9, float on, size (monitor_w*0.5) (monitor_h*0.6), match:class (org.pulseaudio.pavucontrol)
windowrule = opacity 0.9, match:class (kitty)
windowrule = opacity 0.85 override 0.7 override 1 override, match:class (discord|vesktop|org.telegram.desktop)
windowrule = opacity 0.8 override 0.6 override 1 override, match:class (spotify)
#windowrulev2 = opacity 0.85 0.85, class:^(Spotify)$
windowrule = opacity 0.9 override 0.7 override 1 override, match:class (firefox)
#windowrule = opacity 0.8 override 0.6 override 1 override, tag:viewer*
windowrule = opacity 0.8, float on, size 800 500, match:class (clipse)

# LAYER RULES
#layerrule = blur, rofi
#layerrule = ignorezero, rofi
#layerrule = ignorealpha 0.5, rofi
#layerrule = dimaround, rofi
#layerrule = animation popin 10%, rofi
#layerrule = blur, notifications
#layerrule = ignorezero, notifications
layerrule = blur on, ignore_alpha 0.5, match:namespace waybar
#layerrule = ignorezero, waybar
#layerrule = ignorealpha 0.5, tag:notif*
layerrule = blur on, match:namespace logout_dialog

# SWAYNC BLUR & XRAY
layerrule = blur on, ignore_alpha 0.5, xray 0, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0.5, xray 0, match:namespace swaync-notification-window

#FLOAT
#windowrule = float, tag:settings*
#windowrule = float, tag:viewer*
#windowrule = float, tag:multimedia_video*
#windowrule = size 1280 720, tag:multimedia_video*

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# POP UPS AND DIALOGUES
windowrule = float on, size (monitor_w*0.5) (monitor_h*0.6), center on, match:title (Save As|Save a File|Pick Files)

windowrule = float on, size (monitor_w*0.7) (monitor_h*0.6), match:initial_title (Open Files)
